const definitions = {
	"heaven/heaven": {
		1: "This is a time of waiting. Organize and plan your strategy for a future success.",
		2: "You are about to begin a important project. Seek out a person who can help you ensure its success.",
		3: "Hard work and an attention to details will guarantee you reach your goals.",
		4: "Once ready, test your plans, so you may perfect them.",
		5: "Your plan is or will be successful. Revisit allies and look for new leaders.",
		6: "Do not allow your success to over-inflate your ego. If you do there will be a price to pay.",
		number: 1,
		title: "Power",
		definition:
			"The birth of something great is near. You will be an important factor in a new endeavor that will grow and regenerate forever.",
	},
	"earth/earth": {
		1: "Remain cautious and composed. Do not act without forethought. Persistence is your ally.",
		2: "Follow your ethics. Move along your path with confidence.",
		3: "Regardless of your position, you will be respected and rewarded. Take pride in the current state of your life.",
		4: "Speak and act with caution and you will not be defeated or chastised.",
		5: "Your future looks bright.",
		6: "You will survive the power struggles of others. Their winners will make you successful.",
		number: 2,
		title: "Acquiescing",
		definition:
			"Be loyal, diligent, humble and modest in all your undertakings. Never stray from your principles and learn from experience. Perseverance will lead to great things.",
	},
	"water/thunder": {
		1: "Stay focused on your goals. Move forward with your plans. Seek the help of others. Distribute responsibilities and you will overcome all obstacles.",
		2: "Be cautious of what enterprises you enter. Now may not be the time for you to make a move.",
		3: "It may be unwise to move without guidance at this time. Be careful not to lose your way.",
		4: "Partnerships will bring good fortune. Accept the sound offers that come your way.",
		5: "Take small steps toward your goals. Giant leaps may prove disastrous.",
		6: "Don’t allow failures to halt your progress. Focus your energies on that which is good.",
		number: 3,
		title: "Accumulating",
		definition:
			"Gather your strength. Take new directions and push forward. Your beginning might be challenging, but with cautious movement and thought your goals will be reached.",
	},
	"mountain/water": {
		1: "Be firm but not do be overbearing. Provide guidance to those who need it.",
		2: "Be patient with your subordinates and instruct them.",
		3: "Pursuing material gain only will harm you.",
		4: "Keep your mind open to new experiences and knowledge.",
		5: "Teach the inexperienced ones with noble ambitions.",
		6: "Teach those who know less than you. Do not strike the first blow.",
		number: 4,
		title: "Ignorance",
		definition:
			"Make sure subordinates understand you mean what you say. Strict structure and rules will inspire growth.",
	},
	"water/heaven": {
		1: "Avoid enemies. Remain patient. Do not act impulsively.",
		2: "You are ready to act. Do so carefully, but not lose momentum.",
		3: "You are vulnerable to those who would take advantage of you. Isolation is your enemy. Nurture like-minded allies. You may be stuck.",
		4: "Be prepared to act quickly and abandon futile undertakings.",
		5: "You are in the right place for now. Be patient. Positive things are coming your way.",
		6: "Seize unexpected opportunities.",
		number: 5,
		title: "Waiting",
		definition:
			"Now is the time to observe and learn. Patience, honesty and diligence will ensure a bright future. You are close to entering an important endeavor. Your future looks very bright.",
	},
	"heaven/water": {
		1: "State your case to the public static and not in the courts.",
		2: "Do not fight battles you cannot win.",
		3: "Begin your own enterprise. Abandon failing relationships.",
		4: "Avoid conflict with the irrational and taunting.",
		5: "Express your point of view and expect positive feedback.",
		6: "You will have setbacks in the short-term. Be patient.",
		number: 6,
		title: "Litigating",
		definition:
			"Do not be forceful or start fights of any kind. Find compromises. Stay calm and do not think with your emotions. Seek allies.",
	},
	"earth/water": {
		1: "Rely on organization to defeat chaos. Keep things under control. Select capable people to assist you.",
		2: "Your tasks will be important and your talents will be appreciated.",
		3: "Beware of the catastrophic error.",
		4: "Do not make your move until you and your allies are ready. Strengthen your weakest links.",
		5: "Small victories are better than no victories. Seek truces and reconciliations.",
		6: "Once your goal is met you will move to a higher level. Keep yourself amid intelligent people.",
		number: 7,
		title: "Mobilizing Troops",
		definition:
			"Pursue your goals with confidence and determination. Rally allies. Beware of errors.",
	},
	"water/earth": {
		1: "Goodwill is your ally. Good things happen to good people.",
		2: "Nurture long-lasting relationships. Do not burn your bridges behind you.",
		3: "Endeavor to turn your enemies into friends and negative situations into positive ones.",
		4: "Network with people beyond your organization. Ask for help from those you trust.",
		5: "Do not be overbearing. You may alienate those whose minds you try to change.",
		6: "Remain a strong leader but seek a successor to ensure the future success of the project.",
		number: 8,
		title: "Alliance",
		definition:
			"Now is a good time to form partnerships, make new friends and seek new experiences.",
	},
	"wind/heaven": {
		1: "Protect that which you already have. Do not be a bragger. Remain focused.",
		2: "Give credit to those who deserve it. Do not be a spendthrift. Reward those who have helped you. Caring for those around you will take you to new heights.",
		3: "Do not bicker or create discord. The only way to progress is agreement.",
		4: "Do not fight battles without good reason.",
		5: "Remain determined and enthusiastic. Others will rally around your cause.",
		6: "Ensure your allies understand your ideas. Prepare yourself to launch a new project.",
		number: 9,
		title: "Small Savings",
		definition: "The time to act is near. Be prepared!",
	},
	"heaven/lake": {
		1: "Rely on a prudent approach at this time.",
		2: "Remain focused. Digressions may harm you.",
		3: "Edit unsound plans. Be wary of taking more on than you can handle. Delusions of grandeur will harm you.",
		4: "When ready, move forward with caution. Only the fittest will survive. You should be successful.",
		5: "Being unprepared invites disaster.",
		6: "Scrutinize your work with great care. Giving it your best will ensure success.",
		number: 10,
		title: "Treading",
		definition: "Test your plans before fully implementing them.",
	},
	"earth/heaven": {
		1: "Do not allow pessimistic people to bring you down. Surround yourself with optimistic people.",
		2: "Reward the skilled. Do not promote those who do not deserve it.",
		3: "Remain steadfast during difficult periods. Better times will come your way.",
		4: "A wonderful venture may be before you. Use your allies to ensure your idea's success. Share the wealth.",
		5: "Ally or merge with like companies.",
		6: "Cure in-house problems from within. Eliminate disloyalty and dishonesty.",
		number: 11,
		title: "Prominence",
		definition:
			"Don't worry about setbacks. You are on the right path. Remain focused and ethical.",
	},
	"heaven/earth": {
		1: "The results will be positive if you disassociate yourself from the dishonest and malicious.",
		2: "Do not play into flattery. It will only corrupt you. Remain honest with yourself and all others.",
		3: "Beware of deception and wary of those whose words do not match their behavior.",
		4: "Assume responsibility for change. Make your world a better place.",
		5: "Move forward with your allies as a single unit. Success will come.",
		6: "All obstructions will clear. Success is waiting for you.",
		number: 12,
		title: "Adversity",
		definition:
			"Do not allow oppressive people to block your development. Free yourself from their influence.",
	},
	"heaven/fire": {
		1: "Make new friends and partners. They will introduce you to prospects.",
		2: "Do not be afraid of new partnerships and allies.",
		3: "Understand your competition. Do not strike until you can win.",
		4: "Humility and goodwill are admirable qualities. Do not humiliate those whom you defeat.",
		5: "Once your deeds are accomplished, celebrate your success with joy.",
		6: "When you win, show compassion toward the loser.",
		number: 13,
		title: "Assembling People",
		definition:
			"Quietly bring your allies together. Prepare to bring your ideas into reality. A great adventure lies before you.",
	},
	"fire/heaven": {
		1: "Never underestimate your competition. Some hard moments will arise.",
		2: "Seek support to ensure your success.",
		3: "Expect rewards for a job well done.",
		4: "Humility will allow you to avoid the jealousy and gossip of others.",
		5: "Treat others as you would have them treat you. Sincerity breeds loyalty.",
		6: "You will be a leader. Good things await you.",
		number: 14,
		title: "Great Reward",
		definition:
			"You are in a time of great achievement and prosperity. You will be recognized for your contributions. Do not allow yourself to feel too self-important.",
	},
	"earth/mountain": {
		1: "Do not boast. Quietly move toward your goal.",
		2: "Humility will ensure good fortune.",
		3: "Work quietly and diligently.",
		4: "Follow the examples of those you admire.",
		5: "To ensure wide-spread support, be fair to all.",
		6: "Humility will guarantee great achievements. Speak to all who want to speak to you.",
		number: 15,
		title: "Modesty",
		definition:
			"Remain modest and do not be ruled by your pride. Act in a dignified manner regardless of your position.",
	},
	"thunder/earth": {
		1: "Remain ever ready. Continue to do good work.",
		2: "Look for immediate solutions to obstacles in your path.",
		3: "Do not procrastinate. Loss of time will injure your projects.",
		4: "Do not doubt your actions or decisions. You will do the right thing. Enjoy your success.",
		5: "Remain ethical. Fix your errors and bolster your shortcomings.",
		6: "Prepare for a new project. Dwelling on past glories may harm you.",
		number: 16,
		title: "Satisfying",
		definition:
			"Abide by your instincts. Take action when you sense the time is right.",
	},
	"lake/thunder": {
		1: "When you lead, seek allies. Be true to yourself to ensure success.",
		2: "Do not waste your time with the unworthy and disgruntled.",
		3: "Seek the good so the bad will avoid you.",
		4: "Be selective in who you ally yourself with. Educate subordinates before assigning them responsibilities.",
		5: "Move toward your goal fearlessly. Sincerity will win you friends.",
		6: "Set rules and regulations. Your goals are ready to be obtained.",
		number: 17,
		title: "Following",
		definition:
			"Follow your destiny without hesitation. Make your ideas come to fruition. Stand steadfastly by your ethics. Success is coming.",
	},
	"mountain/wind": {
		1: "Be aggressive in your endeavors. Right wrongs. Avoid developing a bad attitude. Expect success.",
		2: "Throw off deadwood. Prepare to grow.",
		3: "Do not dwell on past failures or fated relationships. Expect to do well.",
		4: "Do not put your trust in questionable people. Seek proficient allies.",
		5: "Build an honorable reputation. This will bring respect and admiration.",
		6: "If you reach new levels, do not expect the allies of your predecessor to follow you.",
		number: 18,
		title: "Decaying",
		definition:
			"Remove yourself from decaying situations. Set new goals and ground rules.",
	},
	"earth/lake": {
		1: "Your achievements will be honored. Expect praise from your family and associates.",
		2: "Remain steadfast in your decisions. A great moment is near.",
		3: "You are close to entering the limelight. Be patient. Preparedness guarantees nothing will go wrong.",
		4: "Your hard work and persistence have paid off. Congratulations!",
		5: "Respect your friends and associates. Keep your best foot forward.",
		6: "Be kind and compassionate toward those you have beaten. Respect friends and family.",
		number: 19,
		title: "Arriving",
		definition:
			"Put your health and finances in the forefront. Expect hardships and challenges.",
	},
	"wind/earth": {
		1: "Choose your path carefully. Ask yourself if it will ultimately be fulfilling. Do this in relationships as well.",
		2: "When entering relationships, follow your heart and intuition.",
		3: "Know your skills and limitations before accepting any new responsibilities.",
		4: "Do not take up questionable opportunities.",
		5: "Develop a sound work ethic built on integrity and fairness. Mentor those around you.",
		6: "Understanding the elements of your personal and business relationships will ensure they flourish.",
		number: 20,
		title: "Observing",
		definition:
			"Do not make impulsive decisions. Observe the behavior of others before making them allies. Take the path you feel best suited for you.",
	},
	"fire/thunder": {
		1: "Make sure the punishment fits the crime.",
		2: "Be fair with others. Don't blow things out of proportion.",
		3: "Be fair. Stand firm on your judgments. Distance yourself from those who may thwart your efforts.",
		4: "Carry out your decisions with confidence. Seek the approval of your superiors.",
		5: "Do not betray your ethics when under pressure. Always be fair.",
		6: "Give others a second chance. Your kindness will bring good things to you.",
		number: 21,
		title: "Gnawing, Chewing",
		definition: "Do not enter new ventures without a binding contract.",
	},
	"mountain/fire": {
		1: "Treat your body and spirit well.",
		2: "Give your best to all endeavors. Mind your appearance and bolster your self-esteem.",
		3: "Spend your money to live better, but never forget material means are not an end unto themselves.",
		4: "Do not take advantage of others. Ensure your proposals benefit all parties concerned. Do not be flamboyant.",
		5: "Do not develop a lavish lifestyle. Reap the rewards of investing your money wisely.",
		6: "Do not overindulge. Keep things simple. Speak the truth.",
		number: 22,
		title: "Adorning",
		definition:
			"Seek new knowledge and awareness. Repair relationships and property.",
	},
	"mountain/earth": {
		1: "Care for your subordinates.",
		2: "Strengthen your foundations before all is lost.",
		3: "Separate yourself from failing ventures. Seek new opportunities.",
		4: "Your situation may be dangerous. Let loose of failing ventures.",
		5: "Remove yourself from those who would harm you.",
		6: "Maintain your integrity throughout difficult times. Be steadfast in your path and good things will come to you.",
		number: 23,
		title: "Stripping",
		definition:
			"Accept change. Focus on correcting problems that hamper your development. Get your relationships back on track.",
	},
	"earth/thunder": {
		1: "Do not dwell on failures. Correct your mistakes and move forward with authority.",
		2: "Take a break. Relax. Try and forgive and forget past offenses.",
		3: "Do not allow false starts to dishearten you. Stay the course and you will succeed.",
		4: "Remain resolute. Do not follow those who have made bad choices.",
		5: "Admit to your mistakes and correct them.",
		6: "Look for a mistake in your planning which may harm you.",
		number: 24,
		title: "Returning",
		definition: "Set backs will pass quickly. Good fortune will be yours.",
	},
	"heaven/thunder": {
		1: "If you are sure you doing the right thing, proceed without fear.",
		2: "Seek a mentor. Work within the boundaries of your current talents.",
		3: "You may experience temporary setbacks. Remain true to yourself and they will pass.",
		4: "Have faith in the future.",
		5: "Do not take rumors seriously. Stay your course and you will succeed.",
		6: "Be cautious. Do not make a move until you are sure you are ready.",
		number: 25,
		title: "Without Wrong Doing",
		definition:
			"Keep some distance from wrongdoers. Remain honorable and all will be well.",
	},
	"mountain/heaven": {
		1: "Be cautious. Expect the unexpected.",
		2: "Your skills cannot be restrained. Go forward with your plans.",
		3: "Your project will meet with success.",
		4: "Attention to detail will ensure the accomplishment of your task.",
		5: "Stay in control and do not be swayed by gossip and rumors.",
		6: "You will accomplish a great task.",
		number: 26,
		title: "Great Gains",
		definition:
			"Now is the time for less thought and more action. Procrastination will cost you the opportunity to succeed.",
	},
	"mountain/thunder": {
		1: "Avoid envy and jealousy. Be proud of your achievements.",
		2: "Make opportunities for those with talent. Seek roots that empower you.",
		3: "Do not choose partners based on their financial status.",
		4: "Do not do unjustified favors or let others influence your decisions.",
		5: "Embrace your ideals. Move slowly toward new endeavors.",
		6: "Put your ideas into action. It is time to realize your goals.",
		number: 27,
		title: "Jaws",
		definition:
			"Speak plainly and sincerely. Feed your hopes and dreams. Nurture others. Do good deeds.",
	},
	"lake/wind": {
		1: "Gain the support and trust of others by demonstrating your good intentions. Humility is your ally.",
		2: "Be courageous in the face of adversity. You will overcome any obstacles.",
		3: "The times may be chaotic and dangerous. If so, be careful.",
		4: "Your problems are not as big as they seem. However, to avoid trouble in the future, handle them carefully.",
		5: "Taking advantage of the unworthy is not noble.",
		6: "Rely on your intuition, diligence and courage to help you through difficult times.",
		number: 28,
		title: "Great Test",
		definition:
			"You may be in a compromised position. Relations and projects may be on the verge of collapsing. It is time to look toward different opportunities.",
	},
	"water/water": {
		1: "Adapt to present conditions. Be patient and the storm will pass.",
		2: "Take small steps toward your goal. Patience and hard work will move you past adversity.",
		3: "Remain calm. Be true to yourself.",
		4: "Be frugal and keep things simple.",
		5: "The problems you now face will soon pass.",
		6: "While your problems may be deep-seated, they will pass.",
		number: 29,
		title: "Cavern",
		definition:
			"Look to your allies for assistance. Take charge of events and move forward confidently.",
	},
	"fire/fire": {
		1: "Do not lose sight of your objectives, friends and acquaintances.",
		2: "Seek modest and diligent people to assist you with your endeavors.",
		3: "Make sure your subordinates follow your rules.",
		4: "Some of your relationships will pass as quickly as they came.",
		5: "Nurture those with talent as well as those you love. This will guarantee success.",
		6: "Be kind to others, but do not allow anyone to hamper your progress.",
		number: 30,
		title: "Brightness",
		definition:
			"Let your intentions be known. Give your charisma free rein. Your future looks bright.",
	},
	"lake/mountain": {
		1: "Understand the intentions of others before allying yourself with them.",
		2: "Do not make friends with those whose motives you do not understand.",
		3: "Seek the truth. Follow that which you know is right.",
		4: "Do not be indecisive. Adhere to your plan.",
		5: "Encourage those around you. Celebrate their accomplishments.",
		6: "Mutual understanding leads to fulfilling friendships and partnerships.",
		number: 31,
		title: "Influencing",
		definition:
			"Study the people around you. Win their loyalty with your integrity.",
	},
	"thunder/wind": {
		1: "Give others space. Do not force issues.",
		2: "Do not dwell on the past. Begin anew.",
		3: "Remain moral. Avoid those who are not.",
		4: "Do not pursue endeavors of little value. Search for worthy allies.",
		5: "Choose your friends wisely.",
		6: "Abandon failing relationships.",
		number: 32,
		title: "Constancy",
		definition:
			"Strengthen relationships and friendships. A solid base will guarantee success.",
	},
	"heaven/mountain": {
		1: "Abandon unsatisfying relationships.",
		2: "Move down your path without looking back.",
		3: "Do not let other's need for counsel exhaust you.",
		4: "Pull back from failing relationships. Act decisively. Doubt is your enemy.",
		5: "Do not associate with persons with whom you dislike. This will bring you peace.",
		6: "Leave bad relationships. Your courage to move on will be rewarded.",
		number: 33,
		title: "Retiring",
		definition:
			"Take personal time alone to assess your progress and goals. Evaluate your friends and cut off any deadwood that may exist.",
	},
	"thunder/heaven": {
		1: "Use your talents. Do not hold back or be modest.",
		2: "Take a stand and you will win the day.",
		3: "Do not pursue unworthy endeavors. Focus on opportunities that will lift you to new heights.",
		4: "Move when you are sure you are ready.",
		5: "There will be setbacks, but you will persevere.",
		6: "Be patient and your good work will eventually be rewarded.",
		number: 34,
		title: "Great Strength",
		definition:
			"Your integrity, perseverance and thoroughness will bring you admiration. Set forth on new ideas.",
	},
	"fire/earth": {
		1: "Be kind to all and you will have success.",
		2: "As you rise to new levels, problems may occur. But you will work your way through them.",
		3: "You will gain the trust and appreciation of others.",
		4: "Displaying your talents will ease the suspicions of others.",
		5: "You are in a very stable position. Continue on as you are.",
		6: "Exercise your authority to maintain your position. Punish wrongdoers but do not be excessive.",
		number: 35,
		title: "Promoting",
		definition: "You are moving up.",
	},
	"earth/fire": {
		1: "Do not allow troubles to bring down your spirit. Maintain your principles.",
		2: "Allow allies to help you through troubled times.",
		3: "Do not face troubling situations passively. Act!",
		4: "Leave bad situations behind you.",
		5: "Be patient.",
		6: "Be cautious and avoid bad management.",
		number: 36,
		title: "Brightness Wounded",
		definition: "Remain optimistic. Things will get better.",
	},
	"wind/fire": {
		1: "Establish rules to avoid chaos.",
		2: "Maintain orderly affairs so you can concentrate your energies on your goals.",
		3: "Stiff rules will make all work harder. Work hard. Do not procrastinate.",
		4: "Success comes through working together.",
		5: "Take pride in your responsibilities and attend them well.",
		6: "Lead well. Be firm yet fair and sincere.",
		number: 37,
		title: "Family",
		definition:
			"Understand your position and responsibilities in your family. Stay within your boundaries.",
	},
	"fire/lake": {
		1: "Do not try to reestablish old relationships.",
		2: "Try to resolve disagreements in present relationships.",
		3: "You may lose ground but you will persevere.",
		4: "Difficult times may lie ahead. Seek the wisdom of others.",
		5: "Do not hold grudges. Move on with your life.",
		6: "Do not be afraid to develop new friends and allies.",
		number: 38,
		title: "Misunderstanding",
		definition: "Do not look to win large battles at this time.",
	},
	"water/mountain": {
		1: "Be cautious and do not take action before the time is right.",
		2: "Remain true to yourself and principles even in the face of adversity.",
		3: "Bad times will pass.",
		4: "Do not play the martyr. Ask for help when you feel overwhelmed.",
		5: "Do not be afraid to ask for help.",
		6: "Only assistance from those you trust will see you through. Do not act before you are prepared.",
		number: 39,
		title: "Obstructing",
		definition:
			"Seek counsel from someone you trust. He will assist you through your difficulties.",
	},
	"thunder/water": {
		1: "Move toward your goals with confidence.",
		2: "Maintain your integrity. Focus on your goals and all will be well.",
		3: "Diversify. Do not rely on just one path to find success.",
		4: "The time for action is now. A great adventure lies before you.",
		5: "Proceed with your ideas with optimism.",
		6: "Cut your ties with those who have betrayed you. Proceed with confidence.",
		number: 40,
		title: "Separating",
		definition: "Even without support your plans will come to fruition.",
	},
	"mountain/lake": {
		1: "Care for others and others will care for you.",
		2: "Save money for future needs. Create a budget.",
		3: "Work as an individual but do let others lend a helping hand.",
		4: "Expect improvement in your situation and celebrate.",
		5: "Your leadership will ensure you and others will prosper.",
		6: "Expect to be treated as you treat others.",
		number: 41,
		title: "Decreasing",
		definition:
			"Keep to a tight budget. Avoid the frivolous and you will realize your goals.",
	},
	"wind/thunder": {
		1: "Do not be a spendthrift. Support good causes. The results will bring you satisfaction.",
		2: "Volunteer. Mentor. Be generous with your money.",
		3: "Ask allies for finances when needed.",
		4: "Look for new ventures.",
		5: "Carry out your endeavors with integrity and fairness.",
		6: "Be careful not to be misunderstood.",
		number: 42,
		title: "Increasing",
		definition:
			"Once you are prosperous, pursue goals that were previously out of your reach. Invest in your future.",
	},
	"lake/heaven": {
		1: "Seek alliances with those of influence.",
		2: "Be cautious. Do not error.",
		3: "Disregard the slander of others. Remain ethical and bad times will pass.",
		4: "Learn from your mistakes and seek wise counsel.",
		5: "Cull the immoral from your life.",
		6: "Move toward your goals again. If you do not realize success, rethink your strategy.",
		number: 43,
		title: "Severing",
		definition:
			"State your case to your opposition. Fight for your beliefs.",
	},
	"heaven/wind": {
		1: "Choose your friends and acquaintances carefully.",
		2: "Avoid the company of malicious people.",
		3: "Be watchful of those with low morals but give deserving ones a second chance.",
		4: "Stand up to immorality and negativity.",
		5: "Surround yourself with intelligent, trustworthy people. Remain humble.",
		6: "Take advantage of the conceit of others.",
		number: 44,
		title: "Meeting",
		definition:
			"Judge people by who they are and not by their outward beauty.",
	},
	"lake/earth": {
		1: "Take advantage of high morale. Move toward your goals.",
		2: "Remain sincere. Success is near.",
		3: "Understand the position of your opposition.",
		4: "Continue on your current path and you will succeed.",
		5: "Your ideas will be well received by most others.",
		6: "Even though some do not agree with you, continue on your course.",
		number: 45,
		title: "Gathering",
		definition: "Work with those you trust to achieve great things.",
	},
	"earth/wind": {
		1: "Your kindness and virtue will ensure your success.",
		2: "Share your success with others.",
		3: "Work with a worthy group toward your goals.",
		4: "Be prepared and further success will be inevitable",
		5: "Remain focused. Do not let your success inflate your sense of importance. Move steadily toward your goals.",
		6: "Remain focused. Do not allow your success to lead you off course.",
		number: 46,
		title: "Rising",
		definition: "You will succeed in reaching your goals. Congratulations!",
	},
	"lake/water": {
		1: "Mistakes in your approach may cause setbacks.",
		2: "Do not make impulsive decisions concerning important matters. Remain calm and think things through.",
		3: "Be discreet. Develop a plan for solving your problems alone.",
		4: "Be patient. In time assistance will come.",
		5: "You may lose ground. Do not act with malice. Accept your losses and move on to new things.",
		6: "Evaluate your next move. Do not repeat old mistakes. Move carefully and with optimism and results will be positive.",
		number: 47,
		title: "Confining",
		definition: "Remain optimistic in the face of adversity.",
	},
	"water/wind": {
		1: "Throw off deadwood and start anew.",
		2: "Do not abuse those around you. Treat everyone fairly.",
		3: "Seek allies with good work ethics.",
		4: "Restructure that which you must keep. Become more efficient.",
		5: "Enjoy your new successes.",
		6: "Do not be overbearing to those under your leadership.",
		number: 48,
		title: "The Well",
		definition:
			"Now is the time to counsel with others and create new alliances. Draw from their knowledge.",
	},
	"lake/fire": {
		1: "Plan your goals and ideas well.",
		2: "Now is the time for you to move forward. Put your plans into action.",
		3: "You may meet with resistance to your ideas. However, continue to present them and eventually they will be accepted.",
		4: "Correct your mistakes as soon as possible. Your idea is accepted.",
		5: "Everything will go according to your plans.",
		6: "While you may have some who would like to see you fail, continue on your course and you will realize success.",
		number: 49,
		title: "Reforming",
		definition: "Introduce new ideas into your life.",
	},
	"fire/wind": {
		1: "Eliminate your bad habits and you will become more productive.",
		2: "Do not pay attention to your detractors. It is only your opinion that counts.",
		3: "Now is the time to begin new enterprises.",
		4: "Rectify your errors so they do not impede your new ventures.",
		5: "Separate yourself from negative, selfish people.",
		6: "Stay balanced. Being strict yet benevolent will ensure your success.",
		number: 50,
		title: "The Cauldron",
		definition:
			"Put your plans into action. Obstacles will help perfect them.",
	},
	"thunder/thunder": {
		1: "Radical ideas are about to be introduced. Take time to understand them fully.",
		2: "Those who are overwhelmed may leave for a while.",
		3: "Be open to new ideas.",
		4: "Do not waste time trying to change those who cannot be changed.",
		5: "Be prepared to take risks to move ahead.",
		6: "Do not resist change. It favors you.",
		number: 51,
		title: "Startling",
		definition:
			"Expect startling surprises which will have great influence upon your life.",
	},
	"mountain/mountain": {
		1: "Offer a worthy one sound advice.",
		2: "A relationship with someone will be ruined if you do not advise him.",
		3: "Do not stop that which is already in motion.",
		4: "Try to stop an action before it starts.",
		5: "Consider your words wisely before you speak them.",
		6: "Be diplomatic and act with integrity when giving advice to others.",
		number: 52,
		title: "Stopping",
		definition: "Solicit the attention of those you wish to advise.",
	},
	"wind/mountain": {
		1: "Accept constructive criticism. Improve what you can.",
		2: "You are moving in the proper direction. All seems stable.",
		3: "Be prepared to defend yourself against misfortune.",
		4: "Find a safe haven. Regroup and re-energize before launching new enterprises. Plan carefully.",
		5: "When you meet with success, try something new.",
		6: "Use past successes as a foundation to achieving greater goals.",
		number: 53,
		title: "Gradually Progressing",
		definition:
			"Progress at a steady and capable pace. Pay attention to details and remain committed.",
	},
	"thunder/lake": {
		1: "Remain in charge of your direction.",
		2: "Do not dwell on unpleasantness.",
		3: "Remain proud and carry on through these difficult times.",
		4: "You will be burdened by difficulties for awhile.",
		5: "When new opportunities arise, take them with confidence. You will do well.",
		6: "Maintain your integrity throughout your difficulties.",
		number: 54,
		title: "The Marrying Younger Sister",
		definition: "Difficult times have beset you.",
	},
	"thunder/fire": {
		1: "Time will tell how new relationships will work out.",
		2: "Ignore gossip and inane accusations. Your path is a good one.",
		3: "You have done nothing wrong, so do not fear the accusations of others.",
		4: "Your allies will have a closed ear to malicious rumors about you.",
		5: "You will be recognized as an asset.",
		6: "flaunting your prosperity will alienate your family and friends.",
		number: 55,
		title: "Overshadowing",
		definition:
			"Enjoy your prosperity. However, do not forget that with gain comes responsibilities. Be wise in your spending habits.",
	},
	"fire/mountain": {
		1: "Do not be stingy, small-minded or mean.",
		2: "The road before you is a gentle one.",
		3: "In difficult situations remain composed and be kind.",
		4: "Your days will get better and better.",
		5: "Seek out new opportunities.",
		6: "Do not make fun of other's misfortunes. Remember, it could have been you.",
		number: 56,
		title: "Traveling",
		definition:
			"Throughout your life cherish those moments most memorable.",
	},
	"wind/wind": {
		1: "Do not hesitate. Your determination will bring you success.",
		2: "Be honest when expressing your ideas to others.",
		3: "Do not browbeat people with your ideas lest you will be labeled a zealot.",
		4: "Do not let setbacks stop you. Remain constructive and move forward.",
		5: "Think through your decisions before putting them into action.",
		6: "Be prepared to lose support as you move forward.",
		number: 57,
		title: "Penetrating",
		definition: "Communicate with those in your group.",
	},
	"lake/lake": {
		1: "Remain sincere and good-natured. Be open and comfortable.",
		2: "Address misunderstandings with sincerity.",
		3: "Do not treat people superficially. Be true to yourself and honest to them.",
		4: "Try to solve disagreements through compromise.",
		5: "Know your friends and do not confide in your foes.",
		6: "Reward a job well done.",
		number: 58,
		title: "Pleasing",
		definition: "Be benevolent and nurture harmonious relationships.",
	},
	"wind/water": {
		1: "Act swiftly with determination to forge ahead.",
		2: "If matters become chaotic, stay calm and apply your talents to rectifying that which has gone wrong.",
		3: "Bring your group together to resolve obstacles.",
		4: "Support will come for your cause. Be patient.",
		5: "Share your prosperity with those who helped you gain it.",
		6: "While solving your problems may be costly, they will pass.",
		number: 59,
		title: "Dispersing",
		definition:
			"Take command of your situation and eliminate that which hinders your progress.",
	},
	"water/lake": {
		1: "Stay close to home and cut your spending.",
		2: "When opportunity arises take advantage of it. Be cautious, frugal, but not stingy.",
		3: "Establish a budget for you and your partners to follow.",
		4: "Do not live outside your means. Save.",
		5: "Be frugal. Concentrate more on your spiritual self.",
		6: "Do not be a miser. Spend money where and on whom it is needed.",
		number: 60,
		title: "Regulating",
		definition: "Cut your indulgences until you are back on track.",
	},
	"wind/lake": {
		1: "Learn to trust those around you. Give them the benefit of doubt.",
		2: "Manage fairly and everyone will enjoy success.",
		3: "You may be at a turning point. Think through any plan carefully.",
		4: "Deal with problems swiftly.",
		5: "Do what you must to gain the trust of those around you.",
		6: "Now is a time for action.",
		number: 61,
		title: "Mutually Trusting",
		definition:
			"Develop mutual trust amongst your group. Trust will hasten success.",
	},
	"thunder/mountain": {
		1: "Do not overstep your authority. Understand your position.",
		2: "When needed, take on additional responsibilities without complaint. Use this opportunity to display your talent.",
		3: "Do not act above your rank.",
		4: "Do not overstep your authority or you will encounter problems.",
		5: "Act quickly to resolve whatever problems you run into.",
		6: "Overstepping your boundaries will result in serious consequences.",
		number: 62,
		title: "Small Testing",
		definition:
			"Tend to small matters in order to clear the way to take on larger ventures.",
	},
	"water/fire": {
		1: "Expect a bumpy road ahead. Stay your course and success will be yours.",
		2: "Whatever you lose will be regained.",
		3: "Surround yourself with wise people. They will help you gain success.",
		4: "Trust only those who have proven themselves trustworthy.",
		5: "Push forward toward your goals. The way may seem rough but you will succeed.",
		6: "In time your goals will be achieved.",
		number: 63,
		title: "Already Accomplished",
		definition:
			"Proceed carefully. While your path may seem smooth now, future problems may arise and throw you off course.",
	},
	"fire/water": {
		1: "Perfect your skills and quietly strengthen your position.",
		2: "Do not take risks at this time.",
		3: "Persevere and a great opportunity will come to you.",
		4: "Learn from your enemies as well as your allies. These lessons will ensure success.",
		5: "Adhere to your principles and your goals will be attained.",
		6: "Do not become obsessive about anything. Be open to change.",
		number: 64,
		title: "Not Yet Accomplished",
		definition: "Persevere. Be courageous and observant.",
	},
};

///////////////////////////////////////////////////////////

const bagua = {
	heaven: {
		"yang booleans": [true, true, true],
		images: ["heaven"],
		qualities: [
			"creative",
			"strong",
			"light of day",
			"firmness",
			"inspiring",
			"power",
			"aggression",
			"completion",
		],
		direction: "northwest",
		"family member": "father",
		"body part": "head",
		season: "early winter",
		"time of day": "daytime",
		animal: "horse",
		color: "purple",
		element: "metal",
		"other words": [
			"round",
			"prince",
			"jade",
			"cold",
			"ice",
			"tree fruit",
			"upper garment",
			"word",
			"prehistoric",
			"flesheater",
		],
	},
	earth: {
		"yang booleans": [false, false, false],
		images: ["earth"],
		qualities: [
			"weak",
			"yielding",
			"dark",
			"nurturing",
			"responsive",
			"receptive",
			"adaptable",
			"submissive",
			"charitable",
			"protective",
			"even-tempered",
			"frugal",
			"fertile",
		],
		direction: "southwest",
		"family member": "mother",
		"body part": "belly",
		season: "early autumn",
		"time of day": "night",
		animal: "cow",
		color: "black",
		element: "soil",
		"other words": [
			"cloth",
			"kettle",
			"pregnancy",
			"level",
			"balanced",
			"impartial",
			"large wagon",
			"form",
			"ornament",
			"multitude",
			"shaft",
			"tree trunk",
		],
	},
	fire: {
		"yang booleans": [true, false, true],
		images: ["fire", "sun", "lightning"],
		qualities: [
			"clear",
			"conscious",
			"intelligent",
			"dependent",
			"clinging",
			"illuminating",
			"warming",
			"searing",
		],
		direction: "south",
		"family member": "middle daughter",
		"body part": "eye",
		season: "midsummer",
		"time of day": "noon",
		animal: "pheasant",
		color: "yellow",
		element: "fire",
		"other words": [
			"clarity",
			"coat of mail",
			"helmet",
			"armor",
			"lance",
			"weapons",
			"big-bellied",
			"dryness",
			"tortoise",
			"crab",
			"snail",
			"mussel",
			"sheild-bearing creatures",
			"tree dead at the top",
			"firm without",
			"hollow within",
		],
	},
	water: {
		"yang booleans": [false, true, false],
		images: ["water", "clouds", "rain", "spring", "pit", "chasm"],
		qualities: [
			"dangerous",
			"difficult",
			"profound",
			"anxious",
			"deep",
			"mysterious",
			"damned",
			"persistent",
			"persevering",
			"flexible",
			"melancholy",
			"pervasive",
			"protean",
			"mobile",
			"fluid",
			"driving",
		],
		direction: "north",
		"family member": "middle son",
		"body part": "ear",
		season: "midwinter",
		"time of day": "midnight",
		animal: "pig",
		color: "scarlet",
		element: "wood",
		"other words": [
			"ditches",
			"ambush",
			"bent then straightened",
			"bow",
			"wheel",
			"sick heart",
			"earache",
			"blood",
			"stumbling horse",
			"wrecked chariot",
			"moon",
			"thieves",
			"hardwood",
			"toil",
		],
	},
	lake: {
		"yang booleans": [false, true, true],
		images: ["lake", "marsh"],
		qualities: [
			"satisfied",
			"fulfilled",
			"excessive",
			"open",
			"pleasing",
			"joyous",
			"magical",
			"elfin",
			"mischievous",
		],
		direction: "west",
		"family member": "youngest daughter",
		"body part": "mouth",
		season: "late autumn",
		"time of day": "dusk",
		animal: "sheep",
		color: "blue",
		element: "flesh",
		"other words": [
			"sorceress",
			"tongue",
			"smashing",
			"breaking apart",
			"dropping off",
			"bursting open",
			"hard salty soil",
			"concubine",
			"ripe fruit",
			"goat",
			"gypsy",
		],
	},
	mountain: {
		"yang booleans": [true, false, false],
		images: ["mountain"],
		qualities: [
			"tranquil",
			"immobile",
			"still",
			"perverse",
			"waiting",
			"patient",
			"calm",
			"stubborn",
			"inert",
			"methodical",
			"eternal",
		],
		direction: "northeast",
		"family member": "youngest son",
		"body part": "hand",
		season: "late winter",
		"time of day": "dawn",
		animal: "dog",
		color: "emerald green",
		element: "stone",
		"other words": [
			"byway",
			"mountain path",
			"pebbles",
			"doorway",
			"opening",
			"gateway",
			"seed of fruit",
			"eunuch",
			"watchman",
			"doorkeeper",
			"fingers",
			"rat",
			"black-billed bird",
			"gnarled tree",
		],
	},
	thunder: {
		"yang booleans": [false, false, true],
		images: ["thunder"],
		qualities: [
			"arousing",
			"activity",
			"excitement",
			"growth",
			"expanding",
			"impulsive",
			"provocative",
			"adventurous",
			"experimental",
			"vehement",
			"influential",
			"persuasive",
			"seductive",
			"decisive",
		],
		direction: "east",
		"family member": "eldest son",
		"body part": "foot",
		season: "spring",
		"time of day": "early morning",
		animal: "dragon",
		color: "amber",
		element: "grass",
		"other words": [
			"spreading out",
			"blossoming",
			"great road",
			"green bamboo",
			"reed",
			"rush",
			"pod-bearing plants",
		],
	},
	wind: {
		"yang booleans": [true, true, false],
		images: ["wind", "wood"],
		qualities: [
			"gentle",
			"penetrating",
			"gradual",
			"honest",
			"simple",
			"subtle",
			"transitory",
			"shifting",
			"elusive",
			"whispering",
			"caressing",
			"indecisive",
		],
		direction: "southeast",
		"family member": "eldest daughter",
		"body part": "thigh",
		season: "early summer",
		"time of day": "midmorning",
		animal: "rooster",
		color: "white",
		element: "air",
		"other words": [
			"guideline",
			"work",
			"long",
			"high",
			"advance then retreat",
			"odor",
			"gray-haired",
			"broad forehead",
			"white of the eye",
			"close to the grain",
			"threefold return",
		],
	},
};

const lineInfo = {
	9: {
		symbol: (unique) => (
			<div className="changing yang" key={`changing yang ${unique}`}>
				<div></div>
			</div>
		),
		isYang: true,
	},
	8: {
		symbol: (unique) => (
			<div className="yin" key={`yin ${unique}`}>
				<div></div>
				<div></div>
			</div>
		),
		isYang: false,
	},
	7: {
		symbol: (unique) => (
			<div className="yang" key={`yang ${unique}`}>
				<div></div>
			</div>
		),
		isYang: true,
	},
	6: {
		symbol: (unique) => (
			<div className="changing yin" key={`changing yin ${unique}`}>
				<div></div>
				<div></div>
			</div>
		),
		isYang: false,
	},
};

export default bagua;
export { definitions, lineInfo };
